apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: f4dmpnbyx-nodejs-gitops
  description: This is GitOps manifest for f4dmpnbyx-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: f4dmpnbyx-nodejs
    backstage.io/kubernetes-id: f4dmpnbyx-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: f4dmpnbyx-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:f4dmpnbyx-nodejs
